### ISSUE TITLE
MERCURE_PUBLISH_URL

### ISSUE THREAD

**Issue by tpharaoh** [chloebrqt/mercure-demo#12]
you wrote:

> As you can see, the MERCURE_PUBLISH_URL is mercure instead of localhost:3000 : that is because it must point to the mercure container. At the moment, I cannot make it work with writing localhost:3000 : if you have the solution, I'm all ears !

In my project by exposing the ports, I am able to use the URL
```
    ports:
      - "9090:80"
```

Not sure if it resolves in your project but thats in my usual docker file

**Comment by chloebrqt** [comment]
Hello!
I also expose the port in my docker-compose file. 🤔 You mean you can set the env variable MERCURE_PUBLISH_URL with the actual url and not the container name? If so, I wonder why it wasn't working on my side. I'll have to try again some time. Thanks for your message!
